#!/usr/bin/env bash

if [ ! -f build ]; then
   echo 'install must be run within its container folder' 1>&2
   exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

gofmt -w src

cd $CURDIR/src/rlog
go build -o $CURDIR/bin/rlog
echo "build rlog success !!!"

export GOPATH="$OLDGOPATH"
